# config.yml
default_computer: computer1
autowake: true
mac-addresses:
  computer1: "00:11:22:33:44:55"
ip-addresses:
  computer1: "192.168.1.1"
ip-test-timeout: 200

login-messages:
  - "系统检测到您是很久以来第一位登录服务器的玩家,"
  - "这让我们感到非常激动和期待。"
  - "为了给您带来最佳的游戏体验,"
  - "我们正在努力唤醒计算机资源..."
  - "请您稍等片刻，我们马上就好！"
  - ""
  - "在此期间，请您放心，一切都在有序进行中。"
  - "您的支持对我们来说非常重要，"
  - "我们会继续优化和完善服务,"
  - "只为让您享受更流畅、更精彩的游戏体验！"
